version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "${ZOOKEEPER_PORT}:2181"
    networks:
      - kafka-net
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "${KAFKA_PORT}:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:${KAFKA_PORT}
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:${KAFKA_PORT}
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:${ZOOKEEPER_PORT}
      KAFKA_CREATE_TOPICS: "${KAFKA_TOPIC}:1:1"
    networks:
      - kafka-net
  frontend:
    build:
      context: ./
      dockerfile: ./frontend/Dockerfile
    container_name: frontend
    ports:
      - "${FRONTEND_PORT}:8080"
  server:
    build: 
      context: ./
      dockerfile: ./server/Dockerfile
    container_name: server
    depends_on:
      - zookeeper
      - kafka
    ports:
      - "${SERVER_PORT}:8001"
    networks:
      - kafka-net
networks:
  kafka-net:
    driver: bridge
